### ISSUE TITLE
采用 YAML header 作为元数据的书写格式

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/kup#1]
## 背景

需要在 Markdown 文件内添加一些元数据，以便 Kup 正确投递。

考虑到在 Markdown 顶部添加 YAML 格式的元数据已是较为普遍的做法：

- [Jekyll - YAML front matter](http://jekyllrb.com/docs/front-matter/)
- [R Markdown - YAML header](https://bookdown.org/yihui/rmarkdown-cookbook/rmarkdown-anatomy.html)
- [Pandoc - YAML metadata block](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block)

Kup 也打算采用这种方式。

## 示意

```yaml
---
title: The title of this issue
tags:
  - JS
  - RFC
repo: cssmagic/kup
id: 168
---

Markdown 正文
Markdown 正文
Markdown 正文
```
